/**
 * 元模型驱动架构核心（@mmda/core）
 * 产品层：Logic（logic/）+ Data（metaUi / models / net / …）+ UI 契约（ui/，无实现）。
 */
export { DateTime, Duration, Interval } from 'luxon'

// Data：utils / extensions
export * from './utils/is'
export * from './utils/platform'
export * from './utils/formatter'
export * from './utils/localdb'
export * from './utils/pluralize'
export * from './utils/date_range'
export * from './utils/tools'
export * from './utils/entity_bool_expr'
export * from './extensions/string_extensions'
export * from './extensions/datetime_extensions'
export * from './extensions/number_extensions'
export * from './extensions/array_extensions'

// Data：metaUi（含 Module）
export * from './metaui/datatype'
export * from './metaui/metaui_action'
export * from './metaui/metaui_field'
export * from './metaui/metaui_group'
export * from './metaui/metaui_builder'
export * from './metaui/metaui_filter'
export * from './metaui/metaui_service'
export * from './metaui/module'

// Data：models
export * from './models/entity'
export * from './models/file'
export * from './models/flow'
export * from './models/metamodel'
export * from './models/pagination'

// 应用壳（abstract class，不在 logic/）
export * from './mmda_app'

// UI 契约（无 Vue / 皮肤实现）
export * from './ui/props'
export * from './ui/css'
export * from './ui/action'
export * from './ui/overlay'
export * from './ui/builder'
export * from './ui/factory'
export * from './ui/field_factory'
export * from './ui/layout'
export * from './ui/app_side_menu'
export * from './ui/context'
export * from './ui/view'

export * from './ui/builder/dialog'
export * from './ui/builder/list'
export * from './ui/builder/list_view'
export * from './ui/builder/table'
export * from './ui/builder/grid'
export * from './ui/builder/tree'
export * from './ui/builder/explorer'

export * from './ui/factory/signin'
export * from './ui/factory/button'
export * from './ui/factory/floating_action_button'
export * from './ui/factory/drop_down_button'
export * from './ui/factory/split_button'
export * from './ui/factory/text_input'
export * from './ui/factory/text_area'
export * from './ui/factory/number_input'
export * from './ui/factory/autocomplete'
export * from './ui/factory/tag_auto_complete'
export * from './ui/factory/barcode'
export * from './ui/factory/qrcode'
export * from './ui/factory/date_common'
export * from './ui/factory/date_picker'
export * from './ui/factory/date_time_picker'
export * from './ui/factory/time_picker'
export * from './ui/factory/date_range_picker'
export * from './ui/factory/calendar'
export * from './ui/factory/file_link'
export * from './ui/factory/file_uploader'
export * from './ui/factory/image_uploader'
export * from './ui/factory/inplace_editor'
export * from './ui/factory/query_builder'
export * from './ui/factory/signature_pad'
export * from './ui/factory/speech_to_text'
export * from './ui/factory/stepper'
export * from './ui/factory/timeline'
export * from './ui/factory/tree_select'
export * from './ui/factory/tree'
export * from './ui/factory/checkbox'
export * from './ui/factory/switch'
export * from './ui/factory/select_common'
export * from './ui/factory/drop_down_list'
export * from './ui/factory/combo_box'
export * from './ui/factory/multi_select'
export * from './ui/factory/radio_button_group'
export * from './ui/factory/check_box_list'
export * from './ui/factory/card'
export * from './ui/factory/tabs'
export * from './ui/factory/toolbar'
export * from './ui/factory/divider'
export * from './ui/factory/tooltip'
export * from './ui/factory/splitter'
export * from './ui/factory/sidebar'
export * from './ui/factory/context_menu'
export * from './ui/factory/carousel'
export * from './ui/factory/badge'
export * from './ui/factory/message'
export * from './ui/factory/avatar'
export * from './ui/factory/skeleton'
export * from './ui/factory/loading'
export * from './ui/factory/breadcrumb'
export * from './ui/factory/progress_bar'
export * from './ui/factory/slider'
export * from './ui/factory/rating'
export * from './ui/factory/chips'
export * from './ui/factory/masked_text_box'
export * from './ui/factory/one_time_password_input'
export * from './ui/factory/color_picker'
export * from './ui/factory/markdown_editor'
export * from './ui/factory/ai_assistant'
export * from './ui/factory/image_editor'
export * from './ui/factory/kanban'
export * from './ui/factory/ribbon'
export * from './ui/factory/pivot_table'
export * from './ui/factory/chart'
export * from './ui/factory/gantt'
export * from './ui/factory/scheduler'
export * from './ui/factory/diagram'

// Logic
export * from './logic/field_search_options'
export * from './logic/validation'
export * from './logic/validators'
export * from './logic/entity_logic'
export * from './logic/sql_operator'

// Data：net / di
export * from './net/api_problem'
export * from './net/fetch_api'
export * from './net/fetch_api_http'
export * from './net/api_error'
export * from './net/http'
export * from './net/api_client'
export * from './net/oauth_api_client'
export * from './di/dependency'
