import type { UiLogic, UiLogicInit } from '@mmda/vui'

type LogicCtor = new (init: UiLogicInit) => UiLogic<any>
type LogicLoader = () => Promise<LogicCtor>
const logic = <M>(load: () => Promise<M>, name: keyof M): LogicLoader =>
  async () => (await load())[name] as LogicCtor

export const LOGIC_LOADERS: Record<string, LogicLoader> = {
  AlternativeStrategies: logic(() => import('./modules/alternative_strategies/AlternativeStrategyLogic'), 'AlternativeStrategyLogic'),
  Boms: logic(() => import('./modules/boms/BomLogic'), 'BomLogic'),
  DailyReports: logic(() => import('./modules/daily_reports/DailyReportLogic'), 'DailyReportLogic'),
  Docs: logic(() => import('./modules/docs/DocLogic'), 'DocLogic'),
  Equipments: logic(() => import('./modules/equipments/EquipmentLogic'), 'EquipmentLogic'),
  EquipmentChecklists: logic(() => import('./modules/equipment_checklists/EquipmentChecklistLogic'), 'EquipmentChecklistLogic'),
  EquipmentSpareParts: logic(() => import('./modules/equipment_spare_parts/EquipmentSparePartLogic'), 'EquipmentSparePartLogic'),
  EquipmentTallies: logic(() => import('./modules/equipment_tallies/EquipmentTallyLogic'), 'EquipmentTallyLogic'),
  LinesideInventories: logic(() => import('./modules/lineside_inventories/LinesideInventoryLogic'), 'LinesideInventoryLogic'),
  Maintenances: logic(() => import('./modules/maintenances/MaintenanceLogic'), 'MaintenanceLogic'),
  MaintenancePlans: logic(() => import('./modules/maintenance_plans/MaintenancePlanLogic'), 'MaintenancePlanLogic'),
  MaterialHandlingJobs: logic(() => import('./modules/material_handling_jobs/MaterialHandlingJobLogic'), 'MaterialHandlingJobLogic'),
  MaterialRequisitions: logic(() => import('./modules/material_requisitions/MaterialRequisitionLogic'), 'MaterialRequisitionLogic'),
  MaterialReturns: logic(() => import('./modules/material_returns/MaterialReturnLogic'), 'MaterialReturnLogic'),
  MaterialTranses: logic(() => import('./modules/material_transes/MaterialTransLogic'), 'MaterialTransLogic'),
  MaterialTransReasons: logic(() => import('./modules/material_trans_reasons/MaterialTransReasonLogic'), 'MaterialTransReasonLogic'),
  MaterialUsage: logic(() => import('./modules/material_usage/MaterialUsageLogic'), 'MaterialUsageLogic'),
  Plants: logic(() => import('./modules/plants/PlantLogic'), 'PlantLogic'),
  Processes: logic(() => import('./modules/processes/ProcessLogic'), 'ProcessLogic'),
  ProductionEvents: logic(() => import('./modules/production_events/ProductionEventLogic'), 'ProductionEventLogic'),
  ProductionItems: logic(() => import('./modules/production_items/ProductionItemLogic'), 'ProductionItemLogic'),
  ProductionJobs: logic(() => import('./modules/production_jobs/ProductionJobLogic'), 'ProductionJobLogic'),
  ProductionLines: logic(() => import('./modules/production_lines/ProductionLineLogic'), 'ProductionLineLogic'),
  ProductionLots: logic(() => import('./modules/production_lots/ProductionLotLogic'), 'ProductionLotLogic'),
  ProductionOrders: logic(() => import('./modules/production_orders/ProductionOrderLogic'), 'ProductionOrderLogic'),
  ProductionPlans: logic(() => import('./modules/production_plans/ProductionPlanLogic'), 'ProductionPlanLogic'),
  ProductionPlates: logic(() => import('./modules/production_plates/ProductionPlateLogic'), 'ProductionPlateLogic'),
  ProductionSchedule: logic(() => import('./modules/production_schedule/ProductionScheduleLogic'), 'ProductionScheduleLogic'),
  ProductionSchedules: logic(() => import('./modules/production_schedule/ProductionScheduleLogic'), 'ProductionScheduleLogic'),
  ProductionScheduleTasks: logic(() => import('./modules/production_schedule_tasks/ProductionScheduleTaskLogic'), 'ProductionScheduleTaskLogic'),
  ProductionTasks: logic(() => import('./modules/production_tasks/ProductionTaskLogic'), 'ProductionTaskLogic'),
  Products: logic(() => import('./modules/products/ProductLogic'), 'ProductLogic'),
  Projects: logic(() => import('./modules/projects/ProjectLogic'), 'ProjectLogic'),
  ProjectAcceptances: logic(() => import('./modules/project_acceptances/ProjectAcceptanceLogic'), 'ProjectAcceptanceLogic'),
  ProjectCapitals: logic(() => import('./modules/project_capitals/ProjectCapitalLogic'), 'ProjectCapitalLogic'),
  ProjectInspections: logic(() => import('./modules/project_inspections/ProjectInspectionLogic'), 'ProjectInspectionLogic'),
  ProjectInProgresses: logic(() => import('./modules/project_in_progresses/ProjectInProgressLogic'), 'ProjectInProgressLogic'),
  ProjectMaterials: logic(() => import('./modules/project_materials/ProjectMaterialLogic'), 'ProjectMaterialLogic'),
  ProjectSchedule: logic(() => import('./modules/project_schedule/ProjectScheduleLogic'), 'ProjectScheduleLogic'),
  ProjectSchedules: logic(() => import('./modules/project_schedule/ProjectScheduleLogic'), 'ProjectScheduleLogic'),
  ProjectSettlements: logic(() => import('./modules/project_settlements/ProjectSettlementLogic'), 'ProjectSettlementLogic'),
  ProjectTasks: logic(() => import('./modules/project_tasks/ProjectTaskLogic'), 'ProjectTaskLogic'),
  ProjectWorkPackages: logic(() => import('./modules/project_work_packages/ProjectWorkPackageLogic'), 'ProjectWorkPackageLogic'),
  QualityControlStandards: logic(() => import('./modules/quality_control_standards/QualityControlStandardLogic'), 'QualityControlStandardLogic'),
  QualityDefects: logic(() => import('./modules/quality_defects/QualityDefectLogic'), 'QualityDefectLogic'),
  QualityInspectedMaterials: logic(() => import('./modules/quality_inspected_materials/QualityInspectedMaterialLogic'), 'QualityInspectedMaterialLogic'),
  QualityInspections: logic(() => import('./modules/quality_inspections/QualityInspectionLogic'), 'QualityInspectionLogic'),
  RectifiableProducts: logic(() => import('./modules/rectifiable_products/RectifiableProductLogic'), 'RectifiableProductLogic'),
  Rectifications: logic(() => import('./modules/rectifications/RectificationLogic'), 'RectificationLogic'),
  ScadaBlocks: logic(() => import('./modules/scada_blocks/ScadaBlockLogic'), 'ScadaBlockLogic'),
  Shifts: logic(() => import('./modules/shifts/ShiftLogic'), 'ShiftLogic'),
  Sites: logic(() => import('./modules/sites/SiteLogic'), 'SiteLogic'),
  Stations: logic(() => import('./modules/stations/StationLogic'), 'StationLogic'),
  StationPortals: logic(() => import('./modules/station_portals/StationPortalLogic'), 'StationPortalLogic'),
  ToolCategories: logic(() => import('./modules/ToolCategories/ToolCategoryLogic'), 'ToolCategoryLogic'),
  Toolkits: logic(() => import('./modules/toolkits/ToolkitLogic'), 'ToolkitLogic'),
  Tools: logic(() => import('./modules/tools/ToolLogic'), 'ToolLogic'),
  Wbses: logic(() => import('./modules/wbses/WbsLogic'), 'WbsLogic'),
  Workers: logic(() => import('./modules/workers/WorkerLogic'), 'WorkerLogic'),
  WorkingSkills: logic(() => import('./modules/working_skills/WorkingSkillLogic'), 'WorkingSkillLogic'),
  Worksites: logic(() => import('./modules/worksites/WorksiteLogic'), 'WorksiteLogic'),
  WorkCalendars: logic(() => import('./modules/work_calendars/WorkCalendarLogic'), 'WorkCalendarLogic'),
  WorkOrders: logic(() => import('./modules/work_orders/WorkOrderLogic'), 'WorkOrderLogic'),
  WorkTeams: logic(() => import('./modules/work_teams/WorkTeamLogic'), 'WorkTeamLogic'),
  WorkTeamTypes: logic(() => import('./modules/work_team_types/WorkTeamTypeLogic'), 'WorkTeamTypeLogic'),
}

export async function createRepositoryLogic(repository: string, init: UiLogicInit) {
  const loader = LOGIC_LOADERS[repository]
  return loader ? new (await loader())(init) : undefined
}
